[skip pipeline] refactor error handle for csd, export-ldif, and monitor-logs

diff --git a/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-export-ldif.yaml b/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-export-ldif.yaml
--- a/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-export-ldif.yaml
+++ b/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-export-ldif.yaml
@@ -10,11 +10,6 @@ data:
     curl -sS https://storage.googleapis.com/kubernetes-release/release/"${KUBECTL_VERSION}"/bin/linux/amd64/kubectl -o /tmp/kubectl
     chmod +x /tmp/kubectl
 
-    NUM_REPLICAS=$(/tmp/kubectl get statefulset "${K8S_STATEFUL_SET_NAME}" -o jsonpath='{.spec.replicas}')
-
-    START=0
-    END=$((${NUM_REPLICAS} - 1))
-
     LDIF_FILES=
     SERVER="${K8S_STATEFUL_SET_NAME}-1"
     SCRIPT="${HOOKS_DIR}"/90-export-ldif-s3.sh
@@ -22,13 +17,12 @@ data:
 
     echo "Uploading LDIF_FILES on server ${SERVER}"
     /tmp/kubectl exec "${SERVER}" -c pingdirectory -- sh -c "test -x ${SCRIPT} && ${SCRIPT}">"${LOG_FILE}"
+    export_ldif_status=$?
 
-    if test ${?} -eq 0; then
-      # Sending logs to STDOUT
-      cat ${LOG_FILE}
-      LDIF_FILE=$(tail -1 "${LOG_FILE}")
-      test -z "${LDIF_FILES}" && LDIF_FILES="${LDIF_FILE}" || LDIF_FILES="${LDIF_FILES} ${LDIF_FILE}"
-    else
-      echo "Error occurred while uploading LDIF_FILES on server ${SERVER}"
+    # Sending success/ or failure logs to STDOUT
+    cat ${LOG_FILE}
+
+    if test ${export_ldif_status} -ne 0; then
+      echo "Script failed on server ${SERVER} exiting"
       exit 1
     fi
diff --git a/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-monitor-log-upload.yaml b/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-monitor-log-upload.yaml
--- a/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-monitor-log-upload.yaml
+++ b/k8s-configs/ping-cloud/base/pingdirectory/config/configmap-monitor-log-upload.yaml
@@ -16,18 +16,28 @@ data:
     END=$((${NUM_REPLICAS} - 1))
 
     MONITOR_LOG_FILES=
+    ERROR_MSG=
     for i in $(seq ${START} ${END}); do
       SERVER="${K8S_STATEFUL_SET_NAME}-${i}"
       SCRIPT="${HOOKS_DIR}"/82-upload-monitor-s3.sh
-      CONTAINER_LOG_FILE=/tmp/upload.log
+      MONITOR_LOG_FILE=/tmp/upload.log
 
       echo "Uploading monitor logs on server ${SERVER}"
-      /tmp/kubectl exec "${SERVER}" -c pingdirectory -- sh -c "test -x ${SCRIPT} && ${SCRIPT}" > "${CONTAINER_LOG_FILE}"
+      /tmp/kubectl exec "${SERVER}" -c pingdirectory -- sh -c "test -x ${SCRIPT} && ${SCRIPT}" > "${MONITOR_LOG_FILE}"
+      monitor_log_status=$?
 
-      if test ${?} -eq 0; then
+      if test ${monitor_log_status} -eq 0; then
         # Sending logs to STDOUT
-        cat ${CONTAINER_LOG_FILE}
+        cat ${MONITOR_LOG_FILE}
       else
-        echo "Upload script not found on server ${SERVER}"
+        # Append last 10 lines to ERROR_MSG
+        MONITOR_LOG_ERROR=$(tail -10 "${MONITOR_LOG_FILE}")
+        ERROR_MSG="${ERROR_MSG} ${MONITOR_LOG_ERROR}"
       fi
     done
+
+    if [ -n "${ERROR_MSG}" ]; then
+      echo "${ERROR_MSG}"
+      echo "Script failed exiting"
+      exit 1
+    fi
